replicaCount: 1
clientImage:
  repository: arshsharma/todolist-client
  tag: b510d7deb3cbcb8787d74ef890c5f255ddb50b26
serverImage:
  repository: arshsharma/todolist-server
  tag: b510d7deb3cbcb8787d74ef890c5f255ddb50b26
dbImage: "postgres"